### ISSUE TITLE
Ability to send mail from any address from one client

### ISSUE THREAD

**Issue by Philatelistguy** [muety/mailwhale#22]
Hi,
It would be great to havve the ability to send mail from any address that is specified in the From header in the rest api request.

**Comment by muety** [comment]
Thanks for your feedback! Not being able to set arbitrary sender addresses is intentional to prevent from being classified as spam and harming the sending mail server's reputation. You can configure custom sender addresses per client on the web interface's "E-Mail Addresses" tab. Additionally disabling `verify_senders` on the server side (not recommended) then comes close to what you requested. Hope that helps!
